name: Fetch products.json hourly (multiple URLs)

permissions:
  contents: write

on:
#   schedule:
#     # - cron: "0 * * * *"   # every hour
#     - cron: "0 0 * * *"   # every day at 00:00 UTC
#   push:
#     branches:
#       - main
#       - database
  workflow_dispatch:

env:
  URLS: |
    https://aquaticarts.com
    https://monsteraquariumon9.com
    https://ckfishworld.com
    https://aquahuna.com
    https://nationwideaquaticsusa.com
    https://enchantedgrow.com
    https://shrimpybusiness.com
    https://flipaquatics.com
    https://aquariumfish.com
    https://imperialtropicals.com
    https://dakuaquatics.com
    https://buceplant.com
    https://dustinsfishtanks.com
    https://aquariumcoop.com
    https://aquariumplantsfactory.com
    https://shop.glassaqua.com
    https://globalexoticquatics.com
    https://aquaticsforfun.com

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Prepare timestamp
        run: |
          echo "DATE=$(date -u +'%Y-%m-%d_%H')" >> $GITHUB_ENV

      - name: Download products.json for all URLs
        run: |
          mkdir -p json

          while read -r URL; do
            [ -z "$URL" ] && continue

            SAFE_URL=$(echo "$URL" | sed 's~https\?://~~' | tr '/' '_')
            mkdir -p "jsons/$SAFE_URL"

            echo "Fetching $URL"
            curl -sS \
              "$URL/products.json?limit=10000" \
              -o "jsons/$SAFE_URL/${DATE}.json"

          done <<< "${URLS}"

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add jsons/

          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Daily products.json snapshots (${DATE})"
            git push
          fi